language: python
python:
#  - 2.7
  - 3.6
  - 3.7
before_install:
  - sudo apt-get update
  - sudo apt-get install g++
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
#  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
#  - chmod +x miniconda.sh
#  - ./miniconda.sh -b -p $HOME/miniconda
#  - export PATH=/home/travis/miniconda/bin:$PATH
#  - conda config --set always_yes yes --set changeps1 no
#  - conda config --add channels conda-forge
#  - conda update -q conda
#  - pip install tqdm
install:
  - conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION numpy scipy cython  six setuptools sphinx numpydoc pkg-config pillow tqdm boltons natsort requests dill pytest theano imageio scikit-learn pandas pytorch hypothesis
#  - conda install -q -n test-env tensorflow=1.13.2
  - conda activate test-env
before_script:
  - conda info
  - conda list
  - pip --version
  - pip freeze
script:
  # Make sure the library installs.
  - python setup.py install
  - python setup.py build_ext --inplace
  - python -c "import pysaliency"  # make sure can be installed without theano, pytorch, and tensorflow
  - conda install theano pytorch
  - pip install tensorflow==1.13.2 schema
  - python -m pytest --nomatlab tests
  - python setup.py sdist
  - pip install dist/*.tar.gz
  - mkdir tmp && cd tmp && python -c "import pysaliency"
